# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_auto_20161008_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_state',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
